#!/bin/sh

read -p "msg: " msg
source $HOME/.config/polybar/modules/locket

curl -X PUT -H "Content-Type: application/json" --json "{\"password\": \"$password\", \"msg\": \"$msg\"}" http://cubercube.ru:8080/api/v1/user/$id

echo "set $msg"